name: Check CIRCEL support scripts

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - ./.devcontainer/**
      - ./circel/support/**
    branches:
      - main

jobs:
  shellcheck-helper-scripts:
    name: Run ShellCheck on helper scripts
    runs-on: ubuntu-latest

    strategy:
      matrix:
        devcontainer-name: ["circel"]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run ShellCheck
      run: |
        curl -Lso shellcheck.tar.xz https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.linux.x86_64.tar.xz
        tar -xf shellcheck.tar.xz --strip-components=1
        ./shellcheck --version
        ./shellcheck .devcontainer/devcontainer-helper circel/support/cmake-helper
      # Run shellcheck in the devcontainer to ensure it is consistent and document the canonical command to run formatting locally.
    - name: Make devcontainer '${{ matrix.devcontainer-name }}' singular
      run: .devcontainer/devcontainer-helper --make-singular ${{ matrix.devcontainer-name }}
    - name: Shellcheck scripts in devcontainer
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: |
          shellcheck --version
          shellcheck .devcontainer/devcontainer-helper circel/support/cmake-helper
